### ISSUE TITLE
Saved weights provided in Google Drive are not in same size as model2.py

### ISSUE THREAD

**Issue by arjunarao619** [anishmadan23/deep3d-pytorch#2]
I was trying to execute the eval.py file using the trained weights given in the repo. I get an error which briefly says:

- There are missing keys in the state_dict
- Unexpected keys in state_dict
- size of the checkpoint param is ([256, 256, 3, 3]) while the shape in current model is torch.Size([256]).

The complete error message while running eval.py (after successfuly running train_test_split.py, dataloader.py, and train.py (for a few iterations since I'm using my cpu)) is:

`RuntimeError: Error(s) in loading state_dict for Deep3d:
	Missing key(s) in state_dict: "module_1.1.weight", "module_1.1.bias", "module_1.1.running_mean", "module_1.1.running_var", "module_1.3.weight", "module_1.3.bias", "module_1.4.weight", "module_1.4.bias", "module_1.4.running_mean", "module_1.4.running_var", "module_2.1.weight", "module_2.1.bias", "module_2.1.running_mean", "module_2.1.running_var", "module_2.3.weight", "module_2.3.bias", "module_2.4.weight", "module_2.4.bias", "module_2.4.running_mean", "module_2.4.running_var", "module_3.1.weight", "module_3.1.bias", "module_3.1.running_mean", "module_3.1.running_var", "module_3.3.weight", "module_3.3.bias", "module_3.4.running_mean", "module_3.4.running_var", "module_3.6.weight", "module_3.6.bias", "module_3.7.weight", "module_3.7.bias", "module_3.7.running_mean", "module_3.7.running_var", "module_4.1.weight", "module_4.1.bias", "module_4.1.running_mean", "module_4.1.running_var", "module_4.3.weight", "module_4.3.bias", "module_4.4.running_mean", "module_4.4.running_var", "module_4.6.weight", "module_4.6.bias", "module_4.7.weight", "module_4.7.bias", "module_4.7.running_mean", "module_4.7.running_var", "module_5.1.weight", "module_5.1.bias", "module_5.1.running_mean", "module_5.1.running_var", "module_5.3.weight", "module_5.3.bias", "module_5.4.running_mean", "module_5.4.running_var", "module_5.6.weight", "module_5.6.bias", "module_5.7.weight", "module_5.7.bias", "module_5.7.running_mean", "module_5.7.running_var". 
	Unexpected key(s) in state_dict: "module_1.2.weight", "module_1.2.bias", "module_2.2.weight", "module_2.2.bias", "module_3.2.weight", "module_3.2.bias", "module_4.2.weight", "module_4.2.bias", "module_5.2.weight", "module_5.2.bias". 
	size mismatch for module_3.4.weight: copying a param with shape torch.Size([256, 256, 3, 3]) from checkpoint, the shape in current model is torch.Size([256]).
	size mismatch for module_4.4.weight: copying a param with shape torch.Size([512, 512, 3, 3]) from checkpoint, the shape in current model is torch.Size([512]).
	size mismatch for module_5.4.weight: copying a param with shape torch.Size([512, 512, 3, 3]) from checkpoint, the shape in current model is torch.Size([512]).`

**The line which throws an error is:**
`model.load_state_dict(torch.load(weight_file,map_location = torch.device('cpu')))`
I hope its not something wrong with my implementation, since I am running as is. Hoping for some help here!

**Comment by anishmadan23** [comment]
I have updated the eval.py script now. It was loading the model from model2.py but in some previous commits, we shifted it to model_orig.py. You can try now and let us know if you are still facing the same error.

**Comment by arjunarao619** [comment]
I had actually tried to use your old model with the uploaded weights and changed eval.py to what you have updated it to today, and there seems to be an argument mismatch in the model's forward function. This is because, in your model_orig.py, your forward function is:
`def forward(self, x):`
while in your model2.py, forward function is:
`def forward(self, orig_x, x):`

in eval.py, you call the model through:
`output = model(left_orig,left).to("device")`
where you are essentially passing 3 arguments to model_orig.py (including self) which accepts only 2. I was wondering if you have a fix for this issue.

The complete error message I get after reflecting the changes you suggested are:


```
In(12): output = model(left_orig,left).to("device")                                                                                                                                                      
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
~/deep3d-pytorch/eval.py in <module>
----> 1 output = model(left_orig,left).to("device")

~/opt/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    530             result = self._slow_forward(*input, **kwargs)
    531         else:
--> 532             result = self.forward(*input, **kwargs)
    533         for hook in self._forward_hooks.values():
    534             hook_result = hook(self, input, result)

TypeError: forward() takes 2 positional arguments but 3 were given
```
P.S: Thank you for your quick reply. I'm looking forward to your help!

**Comment by arjunarao619** [comment]
Since I don't see an immediate fix to this issue, may I ask which model did you train on and which model did you run eval.py on? For me, training on model2.py works although the loss flattens out in the second. Did you experience this as well?

**Comment by WenhongZhang** [comment]
@arjunarao619 The train.py indicates model2.py is the one that works, model_orig.py is just a tmp model for test. So the saved weights file doesn't  correspond to model2. If you want to run eval.py, just train the model2 and save the weights by yourself.

**Comment by arjunarao619** [comment]
@WenhongZhang  yes I tried training on model2.py and I've gotten some results with 5-6 epochs. Does your generate_depthmap.py have any bugs? I am feeding it the evaluated left image and ground truth right image after running eval.py and the corresponding .ply depth map can't be opened by any viewer... Anyway thanks for the clarification, and I appreciate this Pytorch implementation!

**Comment by zhanghongyong123456** [comment]
> Since I don't see an immediate fix to this issue, may I ask which model did you train on and which model did you run eval.py on? For me, training on model2.py works although the loss flattens out in the second. Did you experience this as well?

In(12): output = model(left_orig,left).to("device")                                                                                                                                                      
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
~/deep3d-pytorch/eval.py in <module>
----> 1 output = model(left_orig,left).to("device")

~/opt/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    530             result = self._slow_forward(*input, **kwargs)
    531         else:
--> 532             result = self.forward(*input, **kwargs)
    533         for hook in self._forward_hooks.values():
    534             hook_result = hook(self, input, result)

TypeError: forward() takes 2 positional arguments but 3 were given


I also got this error when testing, have you modified it, hope it can help me

**Comment by zhanghongyong123456** [comment]
> @WenhongZhang yes I tried training on model2.py and I've gotten some results with 5-6 epochs. Does your generate_depthmap.py have any bugs? I am feeding it the evaluated left image and ground truth right image after running eval.py and the corresponding .ply depth map can't be opened by any viewer... Anyway thanks for the clarification, and I appreciate this Pytorch implementation!


@arjunarao619  @anishmadan23  when i run train.py  i get this error ,i do not why happen？
![image](https://user-images.githubusercontent.com/48466610/153703902-c91cdca0-7512-4460-8749-049687d2cc62.png)
